name: CI / Lint & Test (Subset)

on:
  push:
    branches-ignore:
      - main

jobs:
  subset-checks:
    name: Lint & Test (Subset)
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: "dummy"
      OPENAI_API_KEY: "dummy"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: "2.1.3"

      - name: Install dependencies
        run: poetry install

      - name: Lint (ruff)
        run: poetry run ruff check .

      - name: Format check (black)
        run: poetry run black --check .
