name: CI / Lint & Test (Full)

on:
  pull_request:
    branches:
      - main

jobs:
  full-checks:
    name: Lint & Test (Full)
    runs-on: ubuntu-latest

    env:
      BOT_TOKEN: "dummy"
      OPENAI_API_KEY: "dummy"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: "2.1.3"

      - name: Install full dependencies
        run: poetry install

      - name: Run pre-commit
        run: poetry run pre-commit run --all-files --show-diff-on-failure

      - name: Poetry check
        run: poetry check
