name: CI

on:
  pull_request:
    branches: [main]

jobs:
  lint-and-test:
    name: Lint & Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: abatilo/actions-poetry@v4
        with:
          poetry-version: "2.1.3"

      - name: Install deps (project + dev)
        run: poetry install --with dev

      - name: Run black
        run: poetry run black --check .

      - name: Run ruff
        run: poetry run ruff check .

      - name: Run pytest
        run: poetry run pytest -q
